const {onCall,HttpsError}=require('firebase-functions/v2/https');
const {getAuth}=require('firebase-admin/auth');
const {getFirestore,FieldValue,Timestamp}=require('firebase-admin/firestore');
const {getStorage}=require('firebase-admin/storage');
const db=getFirestore(),auth=getAuth(),bucket=getStorage().bucket();
const MONTHS=new Set(['2026-10','2026-11','2026-12']),STAGES=['before','execution','persistence'],SIX_DAYS=6*24*60*60*1000;
const clean=(v,n=250)=>{const s=String(v??'').trim();if(!s||s.length>n)throw new HttpsError('invalid-argument','Campo obrigatório inválido.');return s;};
async function actor(request,roles){if(!request.auth)throw new HttpsError('unauthenticated','Faça login novamente.');const snap=await db.doc(`users/${request.auth.uid}`).get(),p=snap.data();if(!snap.exists||p.active!==true||!roles.includes(p.role))throw new HttpsError('permission-denied','Operação não autorizada.');return {uid:request.auth.uid,...p};}
const callable=(handler,options={})=>onCall({region:'southamerica-east1',memory:'512MiB',timeoutSeconds:120,maxInstances:3,...options},handler);

const importRoutes=callable(async request=>{const admin=await actor(request,['admin']),rows=request.data?.rows;if(!Array.isArray(rows)||!rows.length||rows.length>100)throw new HttpsError('invalid-argument','Envie de 1 a 100 registros.');const batch=db.batch(),seen=new Set();
 for(const raw of rows){const owner=clean(raw.owner,128),date=clean(raw.date,10),month=date.slice(0,7),sourceId=clean(raw.sourceId,40),planned=Number(raw.planned),valid=Number(raw.valid);if(!/^2026-(10|11|12)-\d{2}$/.test(date)||!MONTHS.has(month)||!Number.isInteger(planned)||!Number.isInteger(valid)||planned<0||valid<0||valid>planned)throw new HttpsError('invalid-argument','Registro de rota inválido.');const id=`${date}_${owner}`;if(seen.has(id))throw new HttpsError('already-exists','Promotor repetido na data.');seen.add(id);const [user,existing]=await Promise.all([db.doc(`users/${owner}`).get(),db.doc(`routeDays/${id}`).get()]);const p=user.data();if(!user.exists||p.role!=='promoter'||p.active!==true||p.sourceId!==sourceId)throw new HttpsError('failed-precondition',`Promotor ${sourceId} sem vínculo válido.`);if(existing.exists)throw new HttpsError('already-exists','Roteiro já importado para essa data.');batch.create(db.doc(`routeDays/${id}`),{owner,supervisorId:p.supervisorId,sourceId,date,month,planned,valid,team:String(raw.team??''),createdBy:admin.uid,createdAt:FieldValue.serverTimestamp()});}
 await batch.commit();return {count:rows.length};});

const createConquest=callable(async request=>{const promoter=await actor(request,['promoter']),month=clean(request.data?.month,7),clientCode=clean(request.data?.clientCode,64),title=clean(request.data?.title,100);if(!MONTHS.has(month))throw new HttpsError('invalid-argument','Mês fora da campanha.');const client=await db.doc(`clients/${clientCode}`).get();if(!client.exists)throw new HttpsError('not-found','Cliente não encontrado.');const ref=db.collection('conquests').doc();await ref.create({owner:promoter.uid,supervisorId:promoter.supervisorId,month,clientCode,clientName:client.data().name,title,photos:{},grade:null,reviewedBy:null,reviewedAt:null,nominated:false,createdAt:FieldValue.serverTimestamp()});return {id:ref.id};});

const confirmEvidence=callable(async request=>{const promoter=await actor(request,['promoter']),id=clean(request.data?.conquestId,128),stage=clean(request.data?.stage,20);if(!STAGES.includes(stage))throw new HttpsError('invalid-argument','Etapa inválida.');const path=`conquests/${promoter.uid}/${id}/${stage}`,[exists]=await bucket.file(path).exists();if(!exists)throw new HttpsError('failed-precondition','Foto não localizada.');const [meta]=await bucket.file(path).getMetadata();if(Number(meta.size)>205*1024||!String(meta.contentType).startsWith('image/'))throw new HttpsError('invalid-argument','Arquivo fora do padrão.');await db.runTransaction(async tx=>{const ref=db.doc(`conquests/${id}`),snap=await tx.get(ref),c=snap.data();if(!snap.exists||c.owner!==promoter.uid)throw new HttpsError('not-found','Conquista não encontrada.');if(c.photos?.[stage])throw new HttpsError('already-exists','Evidência já confirmada.');if(stage==='execution'&&!c.photos?.before)throw new HttpsError('failed-precondition','Registre a foto anterior primeiro.');if(stage==='persistence'){const executed=c.photos?.execution?.at?.toMillis?.();if(!executed||Date.now()<executed+SIX_DAYS)throw new HttpsError('failed-precondition','A permanência ainda não completou seis dias.');}tx.update(ref,{[`photos.${stage}`]:{path,size:Number(meta.size),contentType:meta.contentType,at:FieldValue.serverTimestamp()}});});return {ok:true};});

const reviewConquest=callable(async request=>{const supervisor=await actor(request,['supervisor']),id=clean(request.data?.conquestId,128);if(request.data?.grade===''||request.data?.grade===null)throw new HttpsError('invalid-argument','Informe a nota.');const grade=Number(request.data?.grade);if(!Number.isFinite(grade)||grade<0||grade>10)throw new HttpsError('invalid-argument','Nota deve estar entre 0 e 10.');await db.runTransaction(async tx=>{const ref=db.doc(`conquests/${id}`),snap=await tx.get(ref),c=snap.data();if(!snap.exists||c.supervisorId!==supervisor.uid)throw new HttpsError('permission-denied','Conquista fora da sua equipe.');if(!STAGES.every(s=>c.photos?.[s]))throw new HttpsError('failed-precondition','As três evidências são obrigatórias.');if(c.grade!==null)throw new HttpsError('already-exists','Conquista já avaliada.');tx.update(ref,{grade,reviewedBy:supervisor.uid,reviewedAt:FieldValue.serverTimestamp()});});return {ok:true};});

const nominateConquest=callable(async request=>{const promoter=await actor(request,['promoter']),id=clean(request.data?.conquestId,128);await db.runTransaction(async tx=>{const ref=db.doc(`conquests/${id}`),snap=await tx.get(ref),c=snap.data();if(!snap.exists||c.owner!==promoter.uid||c.grade===null||!STAGES.every(s=>c.photos?.[s]))throw new HttpsError('failed-precondition','Conquista não habilitada para indicação.');const nomination=db.doc(`nominations/${c.month}_${promoter.uid}`),old=await tx.get(nomination);if(old.exists)throw new HttpsError('already-exists','Você já indicou uma conquista neste mês.');tx.create(nomination,{month:c.month,owner:promoter.uid,supervisorId:promoter.supervisorId,conquestId:id,createdAt:FieldValue.serverTimestamp()});tx.update(ref,{nominated:true});});return {ok:true};});

const chooseWinner=callable(async request=>{const admin=await actor(request,['admin']),month=clean(request.data?.month,7),conquestId=clean(request.data?.conquestId,128);if(!MONTHS.has(month))throw new HttpsError('invalid-argument','Mês inválido.');const nominations=await db.collection('nominations').where('month','==',month).where('conquestId','==',conquestId).limit(1).get();if(nominations.empty)throw new HttpsError('failed-precondition','Escolha uma conquista indicada.');const nomination=nominations.docs[0].data(),ref=db.doc(`winners/${month}`);if((await ref.get()).exists)throw new HttpsError('already-exists','Mês já encerrado.');await ref.create({month,conquestId,owner:nomination.owner,bonus:50,selectedBy:admin.uid,selectedAt:FieldValue.serverTimestamp()});return {ok:true};});

module.exports={importRoutes,createConquest,confirmEvidence,reviewConquest,nominateConquest,chooseWinner};
