import {routeScore,persistenceDue,canCapture,complete,parseGrade,canNominate,mayReview,visiblePromoters,monthlyScore,dailyRouteProgress} from './domain.js';
import {CLIENT_FIELDS,guessColumns,clientsFromRows,prepareRouteImport} from './import-utils.js';
import {compressCapture} from './photo.js';
const $=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=n=>n===null?'—':n.toLocaleString('pt-BR',{maximumFractionDigits:1});
const date=n=>n==null?'aguardando execução':new Date(n).toLocaleString('pt-BR',{timeZone:'America/Sao_Paulo',dateStyle:'short',timeStyle:'short'});
const months={'2026-10':'Outubro','2026-11':'Novembro','2026-12':'Dezembro'};
const stages={before:'Antes',execution:'Execução',persistence:'Permanência'};
const roles={promoter:'Promotor',supervisor:'Supervisor',admin:'Administrador'};
const users=[{id:'a1',role:'admin',name:'Admin · exemplo',email:'admin@example.invalid'}, {id:'s1',role:'supervisor',name:'Ana · exemplo',email:'ana@example.invalid'}, {id:'s2',role:'supervisor',name:'Pedro · exemplo',email:'pedro@example.invalid'}, {id:'p1',role:'promoter',name:'Marina · exemplo',email:'marina@example.invalid',sourceId:'22',supervisorId:'s1'}, {id:'p2',role:'promoter',name:'Bruno · exemplo',email:'bruno@example.invalid',sourceId:'34',supervisorId:'s1'}, {id:'p3',role:'promoter',name:'Luiza · exemplo',email:'luiza@example.invalid',sourceId:'52',supervisorId:'s2'}];
const clients=new Map([['1001',{code:'1001',name:'Mercado Centro · exemplo',city:'Fortaleza',district:'Centro',street:'Rua de exemplo, 100'}],['1002',{code:'1002',name:'Mercado Norte · exemplo',city:'Caucaia',district:'Centro',street:'Rua de exemplo, 200'}]]);
const demoDays=['01','02','05','06','07','08','09','12','13','14','15','16','19','20','21','22','23','26','27','28'];
let routes=[{owner:'p1',missed:5},{owner:'p2',missed:11},{owner:'p3',missed:0}].flatMap(p=>demoDays.map((day,i)=>({owner:p.owner,month:'2026-10',date:`2026-10-${day}`,valid:i<p.missed?4:5,planned:5,demo:true})));
const photos=()=>({before:{at:'2026-10-02T11:00:00Z',sample:true},execution:{at:'2026-10-02T12:00:00Z',sample:true},persistence:{at:'2026-10-08T12:10:00Z',sample:true}});
const conquests=[{id:'EX-001',owner:'p1',month:'2026-10',title:'Ponto extra na entrada',client:clients.get('1001'),description:'Ampliação de espaço com preços visíveis e material de merchandising.',photos:photos(),grade:9,comment:'Boa visibilidade, precificação e manutenção do espaço.',sample:true}, {id:'EX-002',owner:'p1',month:'2026-10',title:'Exposição na gôndola',client:clients.get('1002'),description:'Ganho de duas frentes na linha principal.',photos:{before:{at:'2026-10-07T11:00:00Z',sample:true},execution:{at:'2026-10-07T12:00:00Z',sample:true}},grade:null,comment:'',sample:true}, {id:'EX-003',owner:'p2',month:'2026-10',title:'Ilha de produtos',client:clients.get('1001'),description:'Exposição com material de merchandising.',photos:photos(),grade:null,comment:'',sample:true},{id:'EX-004',owner:'p3',month:'2026-10',title:'Ampliação de frentes',client:clients.get('1002'),description:'Mais espaço na gôndola e etiquetas organizadas.',photos:photos(),grade:8,comment:'Espaço mantido.',sample:true}];
const nominations=new Map(),winners={},imports=[];
let view='inicio',month='2026-10',actor='p1',clientSheet=null,clientPreview=null,routePreview=null,clientQuery='',page=0,stream=null,target=null,toastTimer,busy=false;
const user=()=>users.find(u=>u.id===actor);
const people=()=>visiblePromoters(user(),users);
const visible=c=>people().some(p=>p.id===c.owner);
const mine=()=>conquests.filter(c=>c.month===month&&visible(c));
const name=id=>users.find(u=>u.id===id)?.name||'Não cadastrado';
function toast(text){$('#toast').textContent=text;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').textContent='',7000);}
function heading(title,text,action=''){return `<div class="heading"><div><h1>${title}</h1><p>${text}</p></div>${action}</div>`;}
function stat(label,value,note){return `<article class="stat"><small>${label}</small><strong>${value}</strong><p class="muted">${note}</p></article>`;}
function changeView(next){view=next;page=0;render();}
function refreshActor(){const role=user().role;$('#role').value=role;$('#actor').innerHTML=users.filter(u=>u.role===role).map(u=>`<option value="${u.id}" ${u.id===actor?'selected':''}>${esc(u.name)}</option>`).join('');}
function render(){
 const admin=user().role==='admin';if(['equipe','clientes'].includes(view)&&!admin)view='inicio';
 document.querySelectorAll('[data-view]').forEach(b=>{b.hidden=b.dataset.admin==='true'&&!admin;b.classList.toggle('active',b.dataset.view===view);if(b.dataset.view===view)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current');});
 $('#main').innerHTML=({inicio:home,conquistas:conquestPage,rota:user().role==='promoter'?promoterRoutePage:routePage,mes:monthPage,regras:rules,equipe:teamPage,clientes:clientPage}[view])();
}
function rankings(){return people().map(p=>({p,s:monthlyScore(p.id,month,routes,conquests,winners[month])})).sort((a,b)=>b.s.total-a.s.total||a.p.name.localeCompare(b.p.name));}
function home(){const items=rankings(),list=mine(),allRoutes=routes.filter(r=>r.month===month&&people().some(p=>p.id===r.owner));const valid=allRoutes.reduce((s,r)=>s+r.valid,0),planned=allRoutes.reduce((s,r)=>s+r.planned,0);const approved=list.filter(c=>complete(c)&&c.grade!==null);const bytes=list.reduce((s,c)=>s+Object.values(c.photos).reduce((v,p)=>v+(p.size||0),0),0);
 return heading(user().role==='promoter'?'Cada conquista conta.':'Visão geral da campanha',`${months[month]} · ${user().role==='supervisor'?'Somente seus promotores':user().role==='admin'?'Todos os supervisores e promotores':'Seu resultado individual'}`,user().role==='promoter'?'<button class="primary" data-go="conquistas">+ Nova conquista</button>':'<button class="primary" data-go="rota">Ver roteiros</button>')+
 `<section class="stats">${stat('Cumprimento de rota',fmt(routeScore(valid,planned).percent)+(planned?'%':''),`${valid} de ${planned} visitas válidas`)}${stat('Pontos de conquistas',fmt(approved.reduce((s,c)=>s+c.grade,0)),`${approved.length} conquistas avaliadas`)}${stat('Aguardando avaliação',list.filter(c=>complete(c)&&c.grade===null).length,'Apenas o supervisor responsável dá a nota')}</section>`+
 `<div class="columns"><section class="panel"><div class="panel-head"><h2>Pontuação mensal</h2><span class="badge">Prévia · sem fechamento</span></div><div class="table-wrap"><table><thead><tr><th>Promotor</th><th>Rota</th><th>Conquistas</th><th>Bônus</th><th>Total</th></tr></thead><tbody>${items.map(({p,s})=>`<tr><td>${esc(p.name)}<small class="table-sub">${esc(name(p.supervisorId))}</small></td><td>${fmt(s.points)}</td><td>${fmt(s.conquests)}</td><td>${s.bonus}</td><td><b>${fmt(s.total)}</b></td></tr>`).join('')}</tbody></table></div><p class="muted">Rota + soma das notas aprovadas + 50 pontos para o vencedor do mês. Empates ainda não desempatados.</p></section><aside class="prize"><span class="eyebrow">CONQUISTA DO MÊS</span><div class="bonus">+50 pontos</div><p>Uma indicação por promotor.</p><p class="muted">O vencedor recebe o bônus e a premiação em dinheiro. Valor do prêmio a definir.</p><button data-go="mes">Ver indicações</button></aside></div><section class="panel spaced"><div class="panel-head"><h2>Acompanhamento</h2><span class="badge green">Leve por projeto</span></div><div class="summary-grid"><p><b>${list.length}</b> conquistas registradas</p><p><b>${list.filter(c=>!complete(c)).length}</b> aguardando evidências</p><p><b>${fmt(bytes/1024)} KB</b> de fotos nesta sessão</p></div><p class="muted">Sem uploads nesta demonstração. Até 200 KB por foto e três fotos por conquista. PDF e planilha são processados no navegador.</p></section>`;
}
function conquestPage(){const list=mine();return heading('Conquistas','Antes, execução e permanência. Avaliação pelo supervisor responsável.')+(user().role==='promoter'?`<details class="panel new-conquest"><summary>+ Registrar nova conquista</summary><form id="new-form" class="form-grid"><label>Título<input name="title" maxlength="90" required placeholder="Ex.: ponto extra na entrada"></label><label>Código do cliente<input id="client-code" name="code" maxlength="60" required placeholder="Teste: 1001 ou 1002" autocomplete="off"></label><div class="full client-result" id="client-result">Informe o código para preencher os dados do cliente.</div><label class="full">O que foi conquistado?<textarea name="description" maxlength="500" required></textarea></label><p class="muted full">Responsável pela nota: ${esc(name(user().supervisorId))}. Registro de teste em ${months[month]}.</p><button class="primary">Criar conquista de teste</button></form></details>`:'')+`<div class="conquests">${list.slice(page*12,page*12+12).map(card).join('')||'<div class="panel empty">Nenhuma conquista neste mês.</div>'}</div>${pagination(list.length,12)}`;}
function card(c){const done=complete(c);return `<article class="conquest"><div class="conquest-top"><div><h2>${esc(c.title)}</h2><p class="muted">${esc(c.client.name)} · ${esc(c.client.code)}<br>${esc(c.client.street)} · ${esc(c.client.district)} · ${esc(c.client.city)}<br>${esc(name(c.owner))} · Supervisor: ${esc(name(users.find(u=>u.id===c.owner)?.supervisorId))}</p></div><span class="badge ${done?'green':'amber'}">${c.grade!==null?'Nota '+fmt(c.grade)+'/10':done?'Aguardando nota':'Em acompanhamento'}</span></div><p>${esc(c.description)}</p><div class="steps">${Object.keys(stages).map((stage,i)=>{const p=c.photos[stage],due=persistenceDue(c.photos.execution?.at);return `<div class="step"><b>0${i+1} · ${stages[stage]}</b>${p?`${p.url?`<img loading="lazy" src="${p.url}" alt="${stages[stage]} da conquista">`:''}<p>${date(p.at)}${p.sample?' · Exemplo':` · ${Math.ceil(p.size/1024)} KB`}</p>${p.url?`<button data-photo="${c.id}" data-stage="${stage}">Ver foto</button>`:'<span class="badge">Sem foto real</span>'}`:`<p>${stage==='persistence'&&due?`Liberação: ${date(due)}`:'Capture na loja.'}</p><button data-capture="${c.id}" data-stage="${stage}" ${c.sample||actor!==c.owner||!canCapture(c,stage,Date.now())?'disabled':''}>Abrir câmera</button>`}</div>`;}).join('')}</div>${c.sample?'<p class="muted">Exemplo fictício de fluxo. Crie um registro para testar a câmera.</p>':''}<div class="grade">${c.grade!==null?`<b>Nota: ${fmt(c.grade)} / 10</b><p class="muted">${esc(c.comment)}</p>`:mayReview(user(),c,users)&&done?`<form data-grade="${c.id}"><label>Nota (0–10)<input name="grade" type="number" min="0" max="10" step="0.1" required></label><label>Justificativa<textarea name="comment" maxlength="500" required placeholder="Espaço, precificação e merchandising"></textarea></label><button class="primary">Registrar nota</button></form>`:'<p class="muted">Nota disponível ao supervisor responsável após as três evidências.</p>'}</div></article>`;}
function pagination(total,size){return total>size?`<div class="pagination"><button data-page="${page-1}" ${page===0?'disabled':''}>Anterior</button><span>Página ${page+1} de ${Math.ceil(total/size)}</span><button data-page="${page+1}" ${(page+1)*size>=total?'disabled':''}>Próxima</button></div>`:'';}
function promoterRoutePage(){
 const days=dailyRouteProgress(actor,month,routes);
 const summary=monthlyScore(actor,month,routes,conquests,winners[month]);
 return heading('Meu cumprimento de rota',`${months[month]} · Acompanhe suas lojas previstas e realizadas em cada dia.`)+
 `<section class="panel"><h2>Meu dia a dia</h2>${days.length?`<div class="table-wrap"><table><thead><tr><th scope="col">Dia</th><th scope="col">Lojas previstas</th><th scope="col">Lojas realizadas</th><th scope="col">Cumprimento do dia</th></tr></thead><tbody>${days.map(d=>`<tr><th scope="row">${esc(d.date.split('-').reverse().join('/'))}</th><td>${d.planned}</td><td>${d.valid}</td><td>${d.percent===null?'<span class="badge">Sem rota programada</span>':`<b>${fmt(d.percent)}%</b>`}</td></tr>`).join('')}</tbody></table></div>`:'<p class="empty">Nenhum roteiro importado para você neste mês.</p>'}<p class="muted">Aparecem apenas os dias registrados. Dias ainda não importados não são contabilizados como faltas.</p></section>
 <section class="panel spaced"><h2>Meu percentual do mês · ${months[month]}</h2><div class="stats">${stat('Cumprimento mensal',summary.percent===null?'—':`${fmt(summary.percent)}%`,`${summary.valid} lojas realizadas de ${summary.planned} previstas`)}${stat('Pontos de rota',fmt(summary.points),'Até 100 pontos, com mínimo de 90% no mês.')}</div><p class="muted">O acumulado usa todas as lojas realizadas divididas por todas as previstas no mês, não a média dos percentuais diários.</p></section>`;
}
function routePage(){return heading('Cumprimento de rota','Até 100 pontos. Abaixo de 90%, zero ponto de rota.')+(user().role==='admin'?`<section class="panel"><h2>Importar PDF diário</h2><p class="muted">Estatísticas de check-in/check-out, até 10 MB. Leitura local, sem guardar o PDF.</p><form id="pdf-form" class="form-grid"><label>Arquivo do roteiro<input name="file" type="file" accept=".pdf,application/pdf" required></label><button class="primary" ${busy?'disabled':''}>Ler e conferir PDF</button></form><p id="import-status" role="status"></p></section>${routePreview?routeReview():''}`:'')+`<section class="panel spaced"><h2>${months[month]} · Consolidado</h2><div class="table-wrap"><table><thead><tr><th>Promotor</th><th>Supervisor</th><th>Visitas</th><th>Cumprimento</th><th>Pontos</th></tr></thead><tbody>${rankings().map(({p,s})=>`<tr><td>${esc(p.name)}</td><td>${esc(name(p.supervisorId))}</td><td>${s.valid} / ${s.planned}</td><td>${fmt(s.percent)}${s.percent===null?'':'%'}</td><td><span class="badge ${s.points>=90?'green':'amber'}">${fmt(s.points)}</span></td></tr>`).join('')}</tbody></table></div><p class="muted">Sem arredondar para atingir o mínimo. Dias sem roteiro não geram zero.</p></section>${user().role==='admin'?`<section class="panel spaced"><h2>Histórico das importações</h2>${imports.length?imports.map(i=>`<p>${esc(i.date)} · Equipe ${esc(i.team)} · ${i.count} promotores · ${i.excluded.length} exclusões justificadas</p>`).join(''):'<p class="muted">Nenhum PDF confirmado nesta sessão.</p>'}</section>`:''}`;}
function routeReview(){const r=routePreview;const off=!Object.hasOwn(months,r.month);return `<section class="panel spaced"><div class="panel-head"><h2>Conferência · ${esc(r.date)}</h2><span class="badge">Equipe ${esc(r.team)}</span></div><p class="notice">${off?'Data fora da campanha: a leitura pode ser conferida, mas não será aplicada.':'Revise os vínculos e exclua registros com erro, informando o motivo. Nada foi importado ainda.'} Cores de alerta do PDF não são interpretadas; confira no original.</p><form id="confirm-routes"><div class="table-wrap"><table><thead><tr><th>Incluir</th><th>Promotor no PDF</th><th>Vínculo</th><th>Válidas / previstas</th><th>Conferência / motivo de exclusão</th></tr></thead><tbody>${r.promoters.map((p,i)=>{const match=users.find(u=>u.role==='promoter'&&u.sourceId===p.sourceId);return `<tr><td><input aria-label="Incluir ${esc(p.name)}" name="include-${i}" type="checkbox" ${p.errors.length||!p.planned?'':'checked'} ${p.errors.length||!p.planned?'disabled':''}></td><td>${esc(p.sourceId)} · ${esc(p.name)}</td><td><select aria-label="Vincular ${esc(p.name)}" name="owner-${i}"><option value="">Escolha o promotor</option>${users.filter(u=>u.role==='promoter').map(u=>`<option value="${u.id}" ${match?.id===u.id?'selected':''}>${esc(u.name)}</option>`).join('')}</select></td><td>${p.valid} / ${p.planned}</td><td><small>${esc(p.errors.join(' ')||(!p.planned?'Sem rota programada.':'Sem divergência numérica detectada.'))}</small><input name="reason-${i}" aria-label="Motivo de exclusão ${esc(p.name)}" maxlength="250" placeholder="Obrigatório se excluir" value="${!p.planned?'Sem rota programada':''}"></td></tr>`;}).join('')}</tbody></table></div><label class="check"><input name="confirmed" type="checkbox" required>Conferi os alertas e confirmo que as lojas listadas representam a rota prevista.</label><button class="primary" ${off?'disabled':''}>Confirmar dados na sessão</button><button type="button" id="cancel-routes">Cancelar</button></form></section>`;}
function teamPage(){return heading('Equipe e supervisores','Vincule cada promotor ao responsável pela avaliação.')+`<section class="panel"><h2>Cadastrar usuário de teste</h2><form id="user-form" class="form-grid"><label>Nome<input name="name" required maxlength="100"></label><label>E-mail<input name="email" type="email" required maxlength="150"></label><label>Perfil<select name="role" id="new-role"><option value="promoter">Promotor</option><option value="supervisor">Supervisor</option><option value="admin">Administrador</option></select></label><label>Código no sistema de roteiro<input name="sourceId" id="source-code" maxlength="40" pattern="[0-9]+" required></label><label>Supervisor responsável<select name="supervisorId" id="supervisor-id" required><option value="">Selecione</option>${users.filter(u=>u.role==='supervisor').map(u=>`<option value="${u.id}">${esc(u.name)}</option>`).join('')}</select></label><button class="primary">Cadastrar na sessão</button></form><p class="muted">Não cria login real nem envia convite. O código identifica o promotor nos PDFs.</p></section><section class="panel spaced"><h2>Cadastros</h2><div class="table-wrap"><table><thead><tr><th>Nome</th><th>Perfil</th><th>Código roteiro</th><th>Supervisor</th></tr></thead><tbody>${users.map(u=>`<tr><td>${esc(u.name)}<small class="table-sub">${esc(u.email)}</small></td><td>${roles[u.role]}</td><td>${esc(u.sourceId||'—')}</td><td>${u.role==='promoter'?esc(name(u.supervisorId)):'—'}</td></tr>`).join('')}</tbody></table></div></section>`;}
function clientPage(){const filtered=[...clients.values()].filter(c=>Object.values(c).some(v=>String(v).toLowerCase().includes(clientQuery.toLowerCase())));return heading('Clientes','Importe a base e preencha a conquista pelo código do cliente.')+`<section class="panel"><h2>Importar planilha</h2><p class="muted">XLSX ou CSV, até 5 MB e 20 mil linhas. A primeira aba será utilizada. Os códigos devem estar como texto para preservar zeros à esquerda.</p><form id="clients-form" class="form-grid"><label>Arquivo<input type="file" name="file" accept=".xlsx,.csv" required></label><button class="primary" ${busy?'disabled':''}>Ler planilha</button></form><p id="import-status" role="status"></p></section>${clientSheet?clientMapping():''}${clientPreview?clientReview():''}<section class="panel spaced"><h2>Base de clientes · ${clients.size}</h2><label>Buscar por código, razão social ou endereço<input id="client-search" value="${esc(clientQuery)}" placeholder="Digite e pressione Enter"></label><div class="table-wrap"><table><thead><tr>${Object.values(CLIENT_FIELDS).map(v=>`<th>${v}</th>`).join('')}</tr></thead><tbody>${filtered.slice(page*30,page*30+30).map(c=>`<tr>${Object.keys(CLIENT_FIELDS).map(k=>`<td>${esc(c[k])}</td>`).join('')}</tr>`).join('')}</tbody></table></div>${pagination(filtered.length,30)}</section>`;}
function clientMapping(){const guessed=guessColumns(clientSheet.matrix[0]);return `<section class="panel spaced"><h2>Correspondência das colunas</h2><p class="muted">Aba: ${esc(clientSheet.name)} · ${clientSheet.matrix.length-1} linhas. ${clientSheet.sheets>1?'As outras abas não serão importadas.':''}</p><form id="map-clients" class="form-grid">${Object.entries({...CLIENT_FIELDS,number:'Número do endereço (opcional)'}).map(([key,label])=>`<label>${label}<select name="${key}" ${key==='number'?'':'required'}><option value="">${key==='number'?'Não usar coluna de número':'Selecione a coluna'}</option>${clientSheet.matrix[0].map((h,i)=>h?`<option value="${i}" ${guessed[key]===i?'selected':''}>${esc(h)}</option>`:'').join('')}</select></label>`).join('')}<p class="muted full">O número será juntado à rua. Somente os campos selecionados serão importados; CNPJ e CEP não são necessários à campanha.</p><button class="primary">Conferir clientes</button></form></section>`;}
function clientReview(){const updates=clientPreview.clients.filter(c=>clients.has(c.code)).length;return `<section class="panel spaced"><h2>Prévia da importação</h2><p>${clientPreview.clients.length} registros únicos · ${updates} códigos existentes serão atualizados. Conquistas anteriores manterão o endereço registrado na criação.</p>${clientPreview.identicalDuplicates?`<p class="notice">${clientPreview.identicalDuplicates} linhas repetidas possuem os mesmos dados selecionados e serão unificadas em um cadastro por código. O arquivo original não será alterado.</p>`:''}${clientPreview.errors.length?`<div class="notice">${clientPreview.errors.slice(0,8).map(esc).join('<br>')}<br>Corrija o arquivo e importe novamente. Nenhum dado foi alterado.</div>`:`<p class="muted">${clientPreview.clients.slice(0,5).map(c=>`${esc(c.code)} · ${esc(c.name)} · ${esc(c.street)} · ${esc(c.district)} · ${esc(c.city)}`).join('<br>')}</p><button class="primary" id="confirm-clients" ${!clientPreview.clients.length?'disabled':''}>Confirmar ${clientPreview.clients.length} clientes</button>`}<button id="cancel-clients">Cancelar importação</button></section>`;}
function monthPage(){const ownKey=`${month}|${actor}`,list=mine().filter(c=>canNominate(c,month));return heading('Conquista do mês','Uma indicação por promotor. Prêmio e 50 pontos apenas para o vencedor.')+`<p class="notice">Prévia: somente conquistas concluídas e avaliadas. Escolha do vencedor pela administração, com justificativa. Eleição, desempate e valores finais ainda precisam ser confirmados.</p><section class="panel"><h2>${months[month]} · ${user().role==='promoter'?'Escolha sua indicação':'Indicações'}</h2>${list.map(c=>{const chosen=nominations.get(`${month}|${c.owner}`)===c.id;return `<div class="task"><div><h3>${esc(c.title)}</h3><p>${esc(name(c.owner))} · ${esc(c.client.name)} · Nota ${fmt(c.grade)}</p></div>${user().role==='promoter'?`<button data-nominate="${c.id}" ${winners[month]?'disabled':''}>${nominations.get(ownKey)===c.id?'✓ Indicada':'Indicar'}</button>`:`<span class="badge ${chosen?'green':''}">${chosen?'Indicada':'Não indicada'}</span>`}</div>`;}).join('')||'<p class="empty">Sem conquistas elegíveis neste mês.</p>'}${user().role==='admin'&&!winners[month]?`<form id="winner-form" class="form-grid spaced"><label>Vencedora de teste<select name="conquest" required><option value="">Selecione uma indicada</option>${list.filter(c=>nominations.get(`${month}|${c.owner}`)===c.id).map(c=>`<option value="${c.id}">${esc(name(c.owner))} · ${esc(c.title)}</option>`).join('')}</select></label><label>Justificativa<input name="reason" maxlength="250" required></label><button class="primary">Confirmar vencedora de teste</button></form>`:''}${winners[month]?`<div class="winner"><b>${esc(winners[month].title)}</b><p>${esc(name(winners[month].owner))} · +50 pontos. ${esc(winners[month].reason)}</p></div>`:''}</section>`;}
function rules(){return heading('Regras da campanha','Outubro a dezembro de 2026 · Premiações individuais mensais.')+`<section class="panel rules"><h2>Rota + conquistas + bônus</h2><ul><li>Rota: até 100 pontos. Com menos de 90% de cumprimento, zero neste indicador.</li><li>Conquistas: soma de todas as notas aprovadas do mês, sem média.</li><li>Vencedor da conquista do mês: prêmio e bônus único de 50 pontos.</li><li>Conquista indicada continua contando na soma normal.</li></ul><h2>Registro e avaliação</h2><ul><li>Promotor cadastrado com supervisor responsável. Somente ele atribui a nota de 0 a 10, considerando espaço, precificação e merchandising.</li><li>Cliente identificado pelo código da base importada.</li><li>Três evidências: antes, execução e permanência após 6 dias.</li><li>Até 200 KB por foto, compressão no aparelho.</li></ul><h2>Importações e segurança</h2><p>Apenas a administração acessa cadastro e importação. PDFs são lidos localmente e exigem conferência. Reimportação da mesma equipe/data ou do mesmo promotor/data é bloqueada. Registros com problemas são excluídos com justificativa.</p><p>Os perfis são simulados, não autenticação. Em produção, permissões, nota, selo e intervalo serão validados pelo servidor. Uma foto de tela ainda pode ser capturada pela câmera; selo sozinho não prova autenticidade.</p><h2>Pendências antes da campanha</h2><p>Conectar Firebase e login; testar câmera em celulares; confirmar competência mensal da conquista, fechamento, contestação, desempates, valores dos prêmios e prazo de retenção das fotos. Abaixo de 90% zera apenas rota.</p></section>`;}
function clientLookup(){const c=clients.get($('#client-code').value.trim());$('#client-result').innerHTML=c?`<b>${esc(c.name)}</b><p>${esc(c.street)} · ${esc(c.district)} · ${esc(c.city)}</p>`:'Cliente não encontrado. Peça ao administrador para importar ou revisar a base.';}
document.addEventListener('input',e=>{if(e.target.id==='client-code')clientLookup();});
document.addEventListener('keydown',e=>{if(e.target.id==='client-search'&&e.key==='Enter'){e.preventDefault();clientQuery=e.target.value.trim();page=0;render();}});
document.addEventListener('change',e=>{if(e.target.id==='new-role'){const promoter=e.target.value==='promoter';$('#source-code').required=promoter;$('#source-code').disabled=!promoter;$('#supervisor-id').required=promoter;$('#supervisor-id').disabled=!promoter;}});
document.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b||b.disabled)return;
 try{if(b.dataset.view||b.dataset.go){changeView(b.dataset.view||b.dataset.go);return;}if(b.dataset.page){page=Math.max(0,Number(b.dataset.page));render();return;}
 if(b.dataset.capture){await openCamera(b.dataset.capture,b.dataset.stage);return;}
 if(b.dataset.photo){const c=conquests.find(c=>c.id===b.dataset.photo);if(!visible(c))return;const p=c.photos[b.dataset.stage];$('#full-photo').src=p.url;$('#photo-meta').textContent=`${date(p.at)} · ${Math.ceil(p.size/1024)} KB · Selo local não certificado`;$('#photo-view').showModal();return;}
 if(b.dataset.nominate){const c=conquests.find(c=>c.id===b.dataset.nominate);if(user().role!=='promoter'||c.owner!==actor||!canNominate(c,month)||winners[month])return;nominations.set(`${month}|${actor}`,c.id);render();toast('Indicação atualizada.');}
 if(b.id==='confirm-clients'&&user().role==='admin'&&clientPreview&&!clientPreview.errors.length){clientPreview.clients.forEach(c=>clients.set(c.code,c));clientSheet=null;clientPreview=null;page=0;render();toast('Clientes importados nesta sessão.');}
 if(b.id==='cancel-clients'){clientSheet=null;clientPreview=null;render();}if(b.id==='cancel-routes'){routePreview=null;render();}
 }catch(error){toast(error.message);}
});
document.addEventListener('submit',async e=>{const form=e.target;if(form.method==='dialog')return;e.preventDefault();const data=new FormData(form),requestActor=actor;
 try{
  if(form.id==='new-form'&&user().role==='promoter'){const client=clients.get(data.get('code').trim()),title=data.get('title').trim(),description=data.get('description').trim();if(!client)throw new Error('Código do cliente não encontrado.');if(!title||!description)throw new Error('Preencha o título e a descrição.');conquests.unshift({id:crypto.randomUUID().slice(0,8).toUpperCase(),owner:actor,month,title,client:{...client},description,photos:{},grade:null,comment:'',sample:false});page=0;render();toast('Conquista criada na sessão. Capture a foto de antes.');}
  if(form.dataset.grade){const c=conquests.find(c=>c.id===form.dataset.grade);if(!c||!mayReview(user(),c,users)||!complete(c)||c.grade!==null)throw new Error('Somente o supervisor responsável pode avaliar esta conquista.');const grade=parseGrade(data.get('grade')),comment=data.get('comment').trim();if(!comment)throw new Error('Informe a justificativa.');c.grade=grade;c.comment=comment;c.reviewer=actor;render();toast('Nota somada aos pontos do promotor.');}
  if(form.id==='user-form'&&user().role==='admin'){const role=data.get('role'),name=data.get('name').trim(),email=data.get('email').trim().toLowerCase(),sourceId=String(data.get('sourceId')||'').trim(),supervisorId=data.get('supervisorId');if(!name||!email||!Object.hasOwn(roles,role))throw new Error('Preencha um cadastro válido.');if(users.some(u=>u.email===email))throw new Error('E-mail já cadastrado.');if(role==='promoter'&&(!/^\d+$/.test(sourceId)||!users.some(u=>u.id===supervisorId&&u.role==='supervisor')))throw new Error('Promotor precisa de código numérico e supervisor.');if(role==='promoter'&&users.some(u=>u.sourceId===sourceId))throw new Error('Código de roteiro já cadastrado.');users.push({id:crypto.randomUUID(),role,name,email,...(role==='promoter'?{sourceId,supervisorId}:{})});refreshActor();render();toast('Cadastro e vínculo criados na sessão; login real ainda não conectado.');}
  if(form.id==='winner-form'&&user().role==='admin'){const c=conquests.find(c=>c.id===data.get('conquest')),reason=data.get('reason').trim();if(winners[month]||!c||!canNominate(c,month)||nominations.get(`${month}|${c.owner}`)!==c.id||!reason)throw new Error('Selecione uma indicação válida e justifique.');winners[month]={id:c.id,owner:c.owner,title:c.title,reason};render();toast('Bônus único de 50 pontos aplicado na demonstração.');}
  if(['clients-form','pdf-form'].includes(form.id)&&user().role==='admin'){
   if(busy)return;busy=true;const button=form.querySelector('button');button.disabled=true;const status=$('#import-status');status.textContent='Lendo arquivo no navegador…';
   try{const {readClients,readRoutes}=await import('./importers.js');if(form.id==='clients-form'){const result=await readClients(data.get('file'));if(!result.matrix.length||result.matrix.length<2)throw new Error('Planilha sem dados ou cabeçalhos.');if(actor!==requestActor)return;clientSheet=result;clientPreview=null;}
    else{const result=await readRoutes(data.get('file'),(i,total)=>status.textContent=`Lendo página ${i} de ${total}…`);if(actor!==requestActor)return;routePreview=result;}
    busy=false;render();toast('Leitura concluída. Confira antes de confirmar.');
   }finally{busy=false;button.disabled=false;if($('#import-status'))$('#import-status').textContent='';}
  }
  if(form.id==='map-clients'&&user().role==='admin'){const mapping=Object.fromEntries([...Object.keys(CLIENT_FIELDS),'number'].map(k=>[k,data.get(k)===''?-1:Number(data.get(k))]));clientPreview=clientsFromRows(clientSheet.matrix.slice(1),mapping);render();}
  if(form.id==='confirm-routes'&&user().role==='admin')confirmRoutes(data);
 }catch(error){toast(error.message||'Falha ao processar. Nenhuma importação confirmada.');}
});
function confirmRoutes(data){const r=routePreview;if(!r||!data.has('confirmed'))throw new Error('Confirme o período e a conferência.');const choices=r.promoters.map((p,i)=>({include:data.has(`include-${i}`),owner:data.get(`owner-${i}`),reason:String(data.get(`reason-${i}`)||'')}));const {selected,excluded}=prepareRouteImport(r,choices,users,routes,imports);
 if(!selected.length)throw new Error('Inclua ao menos um promotor válido.');routes=routes.filter(v=>!(v.demo&&v.month===r.month&&selected.some(s=>s.owner===v.owner)));routes.push(...selected);imports.push({date:r.date,team:r.team,count:selected.length,excluded});month=r.month;$('#month').value=month;routePreview=null;render();toast('Roteiro confirmado sem armazenar o PDF. Dados apenas nesta sessão.');
}
$('#month').addEventListener('change',e=>{month=e.target.value;page=0;render();});
$('#role').addEventListener('change',e=>{actor=users.find(u=>u.role===e.target.value).id;page=0;refreshActor();render();});
$('#actor').addEventListener('change',e=>{actor=e.target.value;page=0;render();});
function stopCamera(){stream?.getTracks().forEach(t=>t.stop());stream=null;target=null;$('#video').srcObject=null;$('#snap').disabled=true;}
async function openCamera(id,stage){const c=conquests.find(c=>c.id===id);if(!c||c.sample||c.owner!==actor||user().role!=='promoter'||!canCapture(c,stage,Date.now()))return;target={id,stage,actor,token:crypto.randomUUID()};const expected=target.token;$('#capture-label').textContent=`${stages[stage]} · ${c.title}`;$('#camera-message').textContent='Aguardando permissão da câmera…';$('#snap').disabled=true;$('#capture').showModal();
 try{if(!navigator.mediaDevices?.getUserMedia)throw new Error('A câmera exige HTTPS ou localhost.');const media=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'},width:{ideal:1440}},audio:false});if(!$('#capture').open||target?.token!==expected){media.getTracks().forEach(t=>t.stop());return;}stream=media;$('#video').srcObject=stream;await $('#video').play();$('#snap').disabled=false;$('#camera-message').textContent='Enquadre preços e exposição. A imagem será comprimida a até 200 KB.';}catch(error){$('#camera-message').textContent=error.name==='NotAllowedError'?'Permissão negada. Autorize a câmera e tente novamente.':error.name==='NotFoundError'?'Nenhuma câmera disponível.':error.message;}}
$('#capture').addEventListener('close',stopCamera);
$('#snap').addEventListener('click',async()=>{if(!target||!stream)return;const request={...target},c=conquests.find(c=>c.id===request.id);$('#snap').disabled=true;try{const now=Date.now();if(actor!==request.actor||!canCapture(c,request.stage,now))throw new Error('Etapa não liberada.');const blob=await compressCapture($('#video'),['DEMONSTRAÇÃO · DATA LOCAL NÃO CERTIFICADA',`${date(now)} · ${c.id} · ${stages[request.stage]}`]);if(!$('#capture').open||target?.token!==request.token||actor!==request.actor)return;c.photos[request.stage]={url:URL.createObjectURL(blob),at:new Date(now).toISOString(),size:blob.size};$('#capture').close();render();toast(`Foto de ${Math.ceil(blob.size/1024)} KB. Confira se preços e exposição ficaram legíveis. Não enviada ao servidor.`);}catch(error){toast(error.message);$('#snap').disabled=false;}});
document.addEventListener('visibilitychange',()=>{if(document.hidden&&$('#capture').open)$('#capture').close();});
window.addEventListener('pagehide',()=>{stopCamera();conquests.forEach(c=>Object.values(c.photos).forEach(p=>{if(p.url)URL.revokeObjectURL(p.url);}));});
refreshActor();render();
const toolLifecycle=new AbortController();
if(document.modelContext?.registerTool){
 try{Promise.resolve(document.modelContext.registerTool({
  name:'read_demo_route_scores',title:'Consultar pontuação demonstrativa',
  description:'Consulta os pontos de rota e conquistas dos promotores visíveis para o perfil de teste atual. Não retorna resultado oficial.',
  inputSchema:{type:'object',properties:{month:{type:'string',enum:['2026-10','2026-11','2026-12']}},required:['month'],additionalProperties:false},
  annotations:{readOnlyHint:true,untrustedContentHint:false},
  execute(input){if(!input||!Object.hasOwn(months,input.month)||Object.keys(input).some(k=>k!=='month'))throw new Error('Mês inválido.');return {demo:true,month:input.month,rows:people().map(p=>({id:p.id,name:p.name,...monthlyScore(p.id,input.month,routes,conquests,winners[input.month])}))};}
 },{signal:toolLifecycle.signal})).catch(()=>{});}catch{}
}
window.addEventListener('pagehide',()=>toolLifecycle.abort());
