const DEFAULT_PRIZES={ranking:[800,500,400,300,300,300,200,200,150,150,150,150],conquest:[200,200]};
export function createCampaignRepository({store,db,identity,profile}){
 function access(){const p=profile();if(!p||p.uid!==identity()?.uid)throw Error('Sessão inválida.');return p;}
 async function rows(name,month){const p=access(),parts=[store.where('month','==',month),store.limit(100)];if(p.role==='promoter')parts.push(store.where('owner','==',p.uid));else if(p.role==='supervisor')parts.push(store.where('supervisorId','==',p.uid));const snap=await store.getDocs(store.query(store.collection(db,name),...parts));return snap.docs.map(d=>({id:d.id,...d.data()}));}
 return {
  async dashboard(month){const p=access(),[routes,conquests,winner,config]=await Promise.all([rows('routeDays',month),rows('conquests',month),store.getDoc(store.doc(db,'winners',month)),store.getDoc(store.doc(db,'campaignConfig',month))]);let nominations=[];if(p.role==='admin'){const snap=await store.getDocs(store.query(store.collection(db,'nominations'),store.where('month','==',month),store.limit(100)));nominations=snap.docs.map(d=>({id:d.id,...d.data()}));}else if(p.role==='promoter'){const snap=await store.getDoc(store.doc(db,'nominations',`${month}_${p.uid}`));if(snap.exists())nominations=[{id:snap.id,...snap.data()}];}const owners=[...new Set([...routes,...conquests].map(x=>x.owner))],names={};await Promise.all(owners.map(async uid=>{const u=await store.getDoc(store.doc(db,'users',uid));names[uid]=u.exists()?(u.data().name||u.data().email):uid;}));const saved=config.exists()?config.data():null,prizes=saved?.prizes?.ranking? saved.prizes:DEFAULT_PRIZES;return {routes,conquests,nominations,winner:winner.exists()?winner.data():null,config:{...saved,prizes},names};},
  async resolveRoute(sourceId){access();const code=await store.getDoc(store.doc(db,'routeCodes',String(sourceId)));if(!code.exists())return null;const owner=code.data().owner,user=await store.getDoc(store.doc(db,'users',owner));return user.exists()?{owner,sourceId:String(sourceId),...user.data()}:null;}
 };
}
